version: '3.8'

services:
  moon-db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: moon
      MYSQL_USER: indp
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

  moon-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php_service
    volumes:
      - ./src/php:/var/www/src/php
    ports:
      - "8000:8000"
    depends_on:
      - moon-db

  moon-nginx:
    image: nginx:latest
    container_name: nginx_service
    ports:
      - "80:80" #Python API Interface (.html)
      - "85:85" #laravel
      - "443:443"  # HTTPS port
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf  # nginxの設定ファイル
      - ./src/php:/var/www/src/php  # PHPファイルが置かれる場所
      - ./src/python:/var/www/src/python  # PHPファイルが置かれる場所
    depends_on:
      - moon-php
      - moon-python

  moon-python:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    container_name: python_service
    volumes:
      - ./src/python:/var/www/src/python
    working_dir: /var/www/src/python
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/var/www/src/python:
                   /var/www/src/python/Class:
                   /var/www/src/python/Tests:
                   /var/www/src/python/Util:
                   /var/www/src/python/DataTransferObject:
                   /var/www/src/python/Repository:
                   /var/www/src/python/Service:
                   $PYTHONPATH
    depends_on:
      - moon-db

volumes:
  mysql:
